version: "3"

services:
  frontend:
    build: ./client
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - mern-network
      
  backend:
    build: ./server
    container_name: node-api
    restart: always
    ports: 
      - "5000:5000"
    depends_on:
      - database
    environment:
      - TODO_APP_DATABASE_URI="mongodb+srv://laboratorctt:laboratorctt@ctt.yffcqmt.mongodb.net/?retryWrites=true&w=majority"
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"

networks:
  mern-network:
    driver: bridge