apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment

spec:
  selector:
    matchLabels:
      app: memories
  replicas: 1
  template:
    metadata:
      labels:
        app: memories
    spec:
      containers:
        - name: memories-app
        - image: mydockerid/nameof docker image

apiVersion: v1
kind: Service
metadata:
  name: app-srv
spec:
  type: NodePort
  selector:
    app: memories
  ports:
    - name: memories
    - port: 3000
    - targetPort: 3000 